### Group 5: Does Donald Trump Have Dementia?
A NLP-analysis of "Donald Trump Rev.com Speech Transcripts Dataset", a dataset containing over 500 Donald Trump Speeches from the years of 2015-2024.

In [5]:
#import all the things

import json
from pathlib import Path
import pandas as pd
import matplotlib.pylab as plt
import seaborn as sns

In [6]:
#load dataset

data_dir = Path.cwd() / 'data'
file_path = data_dir / 'Trump_Labeled_Combined_Rev_Speeches_Final_9-24-2024.json'

if not file_path.is_file():
    raise FileNotFoundError(
        f'Missing dataset: {file_path}. See the README for setup instructions.')

with file_path.open('r', encoding='utf-8') as file:
    data = json.load(file)


#convert to csv    

df = pd.DataFrame(data)
df.to_csv(data_dir / 'Trump_Labeled_Combined_Rev_Speeches_Final_9-24-2024.csv', index=False, encoding='utf-8')

In [ ]:
#preview original dataset

df.head(5)

,transcript,title,date,link,word_count,character_count,avg_word_len,stop_word_count,stop_word_rate,non_stopwords,lemmatized,polarity,subjectivity
0,thank you very much. please. thank you. the fi...,abraham-accords-signing-ceremony-transcript-se...,"Sep 15, 2020",https://www.rev.com/transcript-editor/shared/c...,955,4447,4.656545,437,0.457592,thank much please thank first lady honored wel...,thank much please thank first lady honored wel...,0.238266,0.458421
1,"yeah. around that time, yes. maybe a year late...",all-released-portions-of-trumps-10-19-22-depos...,"May 8, 2023",https://www.rev.com/transcript-editor/shared/y...,2977,11520,3.869667,1585,0.532415,yeah around time yes maybe year later thats ri...,yeah around time yes maybe year later thats ri...,0.077526,0.518494
2,thank you very much. appreciate it. thank you ...,amy-coney-barrett-swearing-in-ceremony-transcript,"Oct 26, 2020",https://www.rev.com/transcript-editor/shared/q...,981,4645,4.734964,452,0.460754,thank much appreciate thank much distinguished...,thank much appreciate thank much distinguished...,0.325494,0.526735
3,thank you. . nice to see you. thank you. thank...,cnn-donald-trump-town-hall-5-10-23-transcript,"May 11, 2023",https://www.rev.com/transcript-editor/shared/I...,8392,34149,4.069233,4510,0.537417,thank nice see thank thank thank fantastically...,thank nice see thank thank thank fantastically...,0.102392,0.539212
4,thank you very much everyone. thank you. progr...,coronavirus-task-force-briefing-transcript-mar...,"Mar 17, 2020",https://www.rev.com/transcript-editor/shared/d...,6519,27277,4.184231,3379,0.518331,thank much everyone thank progress made apprec...,thank much everyone thank progress made apprec...,0.186451,0.536127

avg_word_len = average length of words in characters. higher value means he used longer words.

stop_word_rate = stop_word_count / word_count, gives what percentage of the speech are stop words.

non_stopwords = the speech without stopwords

lemmatized = the words of speech transformed into their stem forms

polarity = sentiment-analysis value, negative towards –1, neutral closer to 0, positive closer to +1.

subjectivity = value between 0 to 1 regarding how subjective the speech is, 0 more objective, 1 more subjective.

In [ ]:
#only the original transcript, title and date

trump_speeches = df[['transcript', 'title', 'date']].copy()
trump_speeches.head()

,transcript,title,date
0,thank you very much. please. thank you. the fi...,abraham-accords-signing-ceremony-transcript-se...,"Sep 15, 2020"
1,"yeah. around that time, yes. maybe a year late...",all-released-portions-of-trumps-10-19-22-depos...,"May 8, 2023"
2,thank you very much. appreciate it. thank you ...,amy-coney-barrett-swearing-in-ceremony-transcript,"Oct 26, 2020"
3,thank you. . nice to see you. thank you. thank...,cnn-donald-trump-town-hall-5-10-23-transcript,"May 11, 2023"
4,thank you very much everyone. thank you. progr...,coronavirus-task-force-briefing-transcript-mar...,"Mar 17, 2020"

In [ ]:
#sort the entries after date

trump_speeches['date'] = pd.to_datetime(trump_speeches['date'])
trump_speeches = (trump_speeches.sort_values('date').reset_index(drop=True))


#change the order of the columns

trump_speeches = trump_speeches[['date', 'title', 'transcript']]

In [ ]:
#preview after sorting

trump_speeches.head()

,date,title,transcript
0,2015-07-20,donald-trump-says-i-like-people-who-werent-cap...,excuse me. okay. let’s. you got to let me spea...
1,2016-04-19,donald-trump-michigan-speech-transcript-asks-b...,thank you very much. thank you. thank you. wha...
2,2016-09-26,donald-trump-vs-hillary-clinton-1st-presidenti...,thank you. lester. our jobs are fleeing the co...
3,2016-10-09,donald-trump-vs-hillary-clinton-2nd-presidenti...,"well, i actually agree with that. i agree with..."
4,2016-10-19,donald-trump-vs-hillary-clinton-3rd-presidenti...,"well, first of all, it’s great to be with you ..."